#!/bin/bash

set -eu

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get upgrade -y

apt-get install -qq -y \
  docker.io \
  openssh-server

echo "=> Creating directories"
mkdir -p /mnt/Developer /mnt/secrets

echo "=> Setting up Docker"
cat > tomato.service <<EOF
[Unit]
Description=tomato
Requires=docker.service
After=docker.service
[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill tomato
ExecStartPre=-/usr/bin/docker rm tomato
ExecStartPre=/usr/bin/docker pull davidcelis/tomato:5806771
ExecStart=/usr/bin/docker run -h tomato -e TZ=America/Los_Angeles --net=host --rm -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/Developer:/root/Developer -v /mnt/secrets:/root/secrets --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged --name tomato davidcelis/tomato:5806771
[Install]
WantedBy=multi-user.target
EOF

sudo mv tomato.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable tomato
sudo systemctl start tomato

echo "Done."
