#!/bin/bash

set -e

if [ ! -d ~/Developer/dotfiles ]; then
  echo "Cloning dotfiles..."

  mkdir -p ~/Developer
  cd ~/Developer
  git clone https://github.com/davidcelis/dotfiles.git
fi

cd ~/Developer/dotfiles
git remote set-url origin git@github.com:davidcelis/dotfiles.git

# Symlink dotfiles
make ln

# Install Vim plugins
make vim_plug
vim +'PlugInstall --sync' +qa

# Add SSH config
cat > ~/.ssh/config <<EOF
Host *
  ForwardAgent yes
  IdentityFile /root/.ssh/id_ed25519
  AddKeysToAgent yes
EOF

/usr/sbin/sshd -D
