#!/bin/bash

set -eu

echo "Authenticating 1Password..."
export OP_SESSION_my=$(op signin https://my.1password.com me@davidcel.is --output=raw)

echo "Pulling secrets..."

op get document 'id_ed25519' > id_ed25519
op get document 'local.fish' > local.fish

rm -f ~/.ssh/id_ed25519
rm -f ~/.config/fish/local.fish

ln -s $(pwd)/id_ed25519 ~/.ssh/id_ed25519
chmod 0600 ~/.ssh/id_ed25519
ln -s $(pwd)/local.fish ~/.config/fish/local.fish

eval `ssh-agent -s`
ssh-add ~/.ssh/id_ed25519

echo "Done."
